### ISSUE TITLE
Exception There is no component field [field] in the given Query because of global variable

### ISSUE THREAD

**Issue by superdav42** [KnpLabs/knp-components#90]
I ran into a problem using the get param ?sort=date on almost any page of our site that throw the exception:
Exception There is no component field [date] in the given Query because of global variable in Knp\Component\Pager\Event\Subscriber\Sortable\Doctrine\ORM\Query:56

I traced the problem to:
https://github.com/KnpLabs/knp-components/blob/master/src/Knp/Component/Pager/Event/Subscriber/Sortable/Doctrine/ORM/QuerySubscriber.php#L16

Which uses the global $_GET to see if it should sort the result. The problem is it tries to sort queries that I never intended to sort. I'm actually using the sort param to sort a query that doesn't use the paginator but since it's a global it tries to sort other queries on the page that do use the paginator and throw this error. 

I fixed it by adding this to my config:

```
services:
    knp_paginator.subscriber.sortable:
        class: SomeDummyClass\SortableSubscriber
        scope: request
        tags:
             - { name: 'knp_paginator.subscriber' }      
```

where SomeDummyClass\SortableSubscriber just has empty before function and doesn't register any listeners.

I think all the Sortable subscribers should probably be rewritten to not use global variables and instead pull the sort fields and directions from the options. 

If there's a better way to work around this let me know but since I don't plan on using 
the sorting functions of the paginator turning of the subscribers seems like the best option.

**Comment by gmunumel** [comment]
Hello @superdav42 

I also had the same problem as you. The problem comes from the orderby instruction in knp. I solved mine addind the letter of my name alias in the query. 

For example in my query I have:

```
->from('AcmeBundleBundle:User', 'u')
        ->join('u.rol', 'r')
        ->where('r.id = u.rol')
        ->orderBy('u.'.$sort, 'ASC');
```

Then I call knp_paginator as follows:

```
{{ knp_paginator_sortable(pagination, 'Name', 'u.name') }}
```

That solved my problem. I hope this can help someone else.

**Comment by sudheeshms** [comment]
Yes @gmunumel  said it correct. Thank you for the comment.

**Comment by tgalopin** [comment]
This is a very annoying issue for tests. I think this should be at least somewhere in the documentation (or even better: in the exception) so people can know where the problem comes from. I spent 4 hours debugging this issue.

**Comment by maxailloud** [comment]
I had this error today.
Almost three years after being created it's a long time.

**Comment by OneWeb** [comment]
To solve this I disabled KNP bundle's `sortable` feature in config.yml 

```
knp_paginator:
    default_options:
       sort_field_name: ~ # Disable sorting
```

**Comment by bobalazek** [comment]
I had the same issue when doing functional tests, but none of the solutions above worked for me. After a few hours of trying to solve the issue & looking for solutions, the only thing that did work was unsetting the sort query parameter before the request -- hacky, but it works for me:
```
unset($_GET['sort']);
$crawler = $this->client->request(
    'GET',
    '/admin/users'
 );
```

**Comment by JSkalskiSBG** [comment]
After updating Symfony to 3.3 from 2.7 I had similar error in one of my 'fix' tries.

Using FOS Rest-Bundle for requests from Angular like:

api/examinations?direction=desc&limit=5&page=1*&sort=examination.created_at*

(Examination entity has attribute '$createdAt' mapped to SQL 'created_at')

"There is no such field [created_at] in the given Query component, aliased by [examination]"
It means that you try to sort result by column that does not exist in Entity which you want to sort.


	// Controller
	$queryBuilder = $this->examinationRepository->findAllExaminations();
	$paginator = $this->get('knp_paginator');

	/** @var \Knp\Bundle\PaginatorBundle\Pagination\SlidingPagination $pagination */
	$pagination = $paginator->paginate($queryBuilder, $paramFetcher->get('page'), $paramFetcher->get('limit'));


	// Repository:
    public function findAllExaminations()
    {
        $qb = $this->createQueryBuilder('examination');

        return $qb;
    }



----------------------------------

If you don't really want to 'sort', but it always sorts by parameter 'sort' from URL you should check your *app/config/config.yml*:

knp_paginator:
		page_range: 50                      # default page range used in pagination control
		default_options:
			sort_field_name: sort          # sort field query parameter name
			sort_direction_name: direction # sort direction query parameter name
			distinct: true  

That 'sort_field_name: sort' means it will take parameter 'sort' from GET (maybe also POST) and use it's value as *sort key for every paginator on website!*

**Comment by garak** [comment]
This is fixed in branch 2.0
You can use it righot now by requiring `"knplabs/knp-components": "^2.0@dev"`, or you can wait for a stable release
